### PR TITLE
Add RDMA Write support for SRD connection

### PR DESCRIPTION
**Pull request by YonatanNachum**
Add write support in post send functions, resources creation and destroy and mtu checks.

### CODE REVIEW

**Comment by HassanKhadour** [comment]
Hi @YonatanNachum Thanks for your contribution! , please align the man page with this support

**Comment by YonatanNachum** [comment]
@HassanKhadour 
Hi, Done.
Thanks!

**Comment by HassanKhadour** [comment]
Perftest compilation is failing with this commit due to this error
image

**Comment by HassanKhadour** [comment]
Perftest compilation is failing due to this error:
image

**Comment by YonatanNachum** [comment]
@HassanKhadour 
Hi, sorry.
I accidentally moved a line using EFA direct verb struct out from the ifdef inside perftest_communication.c so it fails the compilation for you.

Thanks.

**Comment by HassanKhadour** [comment]
now I face the following error
image

**Comment by YonatanNachum** [comment]
Updated the PR. I tested it without SRD connection available and it worked.

Thanks.

**Comment by HassanKhadour** [comment]
Thanks for your contribution!

**Pull request merged**
