### PR TITLE
use config.{sub,guess} from system

### PR DESCRIPTION
**Pull request by yetist**
The `config/config.{sub,guess}` files are too old and have not been updated after running `./autogen.sh`.

The easy way is to add the --force option to automake: `automake --foreign --add-missing --copy --force`.

But by doing so, I can't see the effect of the original old files, so I suggest to delete them directly.

### CODE REVIEW

**Comment by talatb** [comment]
Thank you for your change, we will test it on aarch64 system and other archs and update.

**Comment by HassanKhadour** [comment]
Hi, Thank you, We tested it and everything worked correctly,It's ready to be merged.

**Comment by yetist** [comment]
Can this PR be merged?

**Comment by rleon** [comment]
> @HassanKhadour
> 
> Can this PR be merged? Thanks.

It looks like it failed through cracks.

**Pull request merged**
