### PR TITLE
resources: moving all ifdefs around post_send_method inside

### PR DESCRIPTION
**Pull request by lravich**
Signed-off-by: Leonid Ravich <Leonid.Ravich@emc.com>

### CODE REVIEW

**Comment by dimasique1** [comment]
Thanks for the PR, Leonid!

In case of EXP verbs present I see the following error:
src/perftest_resources.c: In function ‘post_send_method’:
src/perftest_resources.c:3682:3: error: ‘err’ undeclared (first use in this function); did you mean ‘erf’?
   err = (ctx->exp_post_send_func_pointer)(ctx->qp[index],
   ^~~
   erf
src/perftest_resources.c:3682:3: note: each undeclared identifier is reported only once for each function it appears in
src/perftest_resources.c:3695:1: warning: no return statement in function returning non-void [-Wreturn-type]
 }
 ^
src/perftest_resources.c: In function ‘run_iter_bw’:
src/perftest_resources.c:3710:23: warning: unused variable ‘bad_wr’ [-Wunused-variable]
  struct ibv_send_wr  *bad_wr = NULL;
                       ^~~~~~
src/perftest_resources.c:3709:27: warning: unused variable ‘bad_exp_wr’ [-Wunused-variable]
  struct ibv_exp_send_wr  *bad_exp_wr = NULL;
                           ^~~~~~~~~~
make[1]: *** [Makefile:852: src/perftest_resources.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/.autodirect/swgwork/dmitryak/upstream_perftest/perftest'
make: *** [Makefile:581: all] Error 2

**Comment by lravich** [comment]
@dimasique1  Sorry , didnt had a chance to compile it case of EXP verbs , any idea how I can do it ? anyway I will update the PR with the errors you found

**Comment by lravich** [comment]
@dimasique1 Done

**Comment by dimasique1** [comment]
Thanks for your contribution, Leonid!!

**Pull request merged**
