### PR TITLE
Fix GPUDirect buffer from being overwritten

### PR DESCRIPTION
**Pull request by aditr**
Signed-off-by: Adit Ranadive <aditr@vmware.com>

### CODE REVIEW

**Comment by zoharbmellanox** [comment]
please indicate in commit description that this commit is fix for commmit :
c2d32eaa44a595b7c10a50a3bddbb3d7179dc0e6

**Comment by aditr** [comment]
Added the Fixes tag. Sorry about that.

**Comment by zoharbmellanox** [comment]
Thanks @aditr 

please make sure that only the bellow commit will be merged.
Fix GPUDirect buffer from being overwritten 

i'm afraid that other commits will be duplicate in the repository.

Thanks,

Zohar

**Comment by xXxSiMoNxXx** [comment]
Hello Adit,

Please abandon this pull request and do a new updated one, if still needed.

Regards,

**Pull request closed without merging**
