### PR TITLE
Support for IPv6 address format in perftest tests

### PR DESCRIPTION
**Pull request by AnandBibhuti**
…rftest.

With this perftest should work fine witn both IPv4 and IPv6 addresses.

Reviewed-by: Ka-Cheong Poon <ka-cheong.poon@oracle.com>

### CODE REVIEW

**Comment by zoharbmellanox** [comment]
Thanks Anand ,
can you describe the usage ? do we have the ability to put ipv6 address as hostname ? 

Could you please add example ? 
is it require any specific system configuration ?

**Comment by AnandBibhuti** [comment]
There is no special configuration needed for it.
In general, IPV6 should be enabled on machines and network files for interfaces
should have IPV6INIT=yes and IPv6 address assigned to IB interfaces.

Following is the example .
(Tests run with single machine as client-server. It works fine too when different machines are clien-server)

~  ip addr show ib0
8: ib0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 65520 qdisc pfifo_fast state UP qlen 4096
    link/infiniband 80:00:02:08:fe:80:00:00:00:00:00:00:00:10:e0:00:01:29:63:81 brd 00:ff:ff:ff:ff:12:40:1b:ff:ff:00:00:00:00:00:00:ff:ff:ff:ff
    inet 10.196.100.134/24 brd 10.196.100.255 scope global ib0
       valid_lft forever preferred_lft forever
    inet6 2001:db8:0:f101::1/64 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::210:e000:129:6381/64 scope link
       valid_lft forever preferred_lft forever


 With current code,
I. Server-
~ ./ib_send_bw
Client -
~ ./ib_send_bw 10.196.100.134

                    Send BW  Test
 Dual-port       : OFF          Device         : mlx4_0
 Number of qps   : 1            Transport type : IB
 Connection type : RC           Using SRQ      : OFF
 TX depth        : 128
 CQ Moderation   : 100
 Mtu             : 2048[B]
 Link type       : IB
 Max inline dat : 0[B]
 rdma_cm QPs     : OFF
 Data ex. method : Ethernet

 local address: LID 0x02 QPN 0x403f2 PSN 0x1eae0a
 remote address: LID 0x02 QPN 0x403f1 PSN 0xb2bebd

 #bytes     #iterations    BW peak[MB/sec]    BW average[MB/sec]   MsgRate[Mpps]
Conflicting CPU frequency values detected: 1600.000000 != 2401.000000. CPU Frequency is not max.
 65536      1000             2780.49            2780.48            0.044488


II. Server-
~ ./ib_send_bw
Client -
~ ./ib_send_bw 2001:db8:0:f101::1
Address family for hostname not supported for 2001:db8:0:f101::1:18515
Problem in resolving basic address and port
Unable to open file descriptor for socket connection Unable to init the socket connection


III. Server-
~ ./ib_send_bw
Client -
~ ./ib_send_bw fe80::210:e000:129:6381%ib0
Address family for hostname not supported for fe80::210:e000:129:6381%ib0:18515
Problem in resolving basic address and port
Unable to open file descriptor for socket connection Unable to init the socket connection

With modified code -

I. Server-
~ /usr/bin/ib_send_bw
Client -
~ ./ib_send_bw 10.196.100.134

 Dual-port       : OFF          Device         : mlx4_0
 Number of qps   : 1            Transport type : IB
 Connection type : RC           Using SRQ      : OFF
 TX depth        : 128
 CQ Moderation   : 100
 Mtu             : 2048[B]
 Link type       : IB
 Max inline data : 0[B]
 rdma_cm QPs     : OFF
 Data ex. method : Ethernet

 local address: LID 0x02 QPN 0x403eb PSN 0x721ac0
 remote address: LID 0x02 QPN 0x403ec PSN 0x91e762

 #bytes     #iterations    BW peak[MB/sec]    BW average[MB/sec]   MsgRate[Mpps]
Conflicting CPU frequency values detected: 2401.000000 != 2133.000000. CPU Frequency is not max.
 65536      1000             2808.48            2808.45            0.044935


II. Server-
~ /usr/bin/ib_send_bw
Client -
~ ./ib_send_bw 2001:db8:0:f101::1

                    Send BW Test
 Dual-port       : OFF          Device         : mlx4_0
 Number of qps   : 1            Transport type : IB
 Connection type : RC           Using SRQ      : OFF
 TX depth        : 128
 CQ Moderation   : 100
 Mtu             : 2048[B]
 Link type       : IB
 Max inline data : 0[B]
 rdma_cm QPs     : OFF
 Data ex. method : Ethernet

 local address: LID 0x02 QPN 0x403ee PSN 0x738c6
 remote address: LID 0x02 QPN 0x403ed PSN 0x5fab9e

 #bytes     #iterations    BW peak[MB/sec]    BW average[MB/sec]   MsgRate[Mpps]
Conflicting CPU frequency values detected: 2401.000000 != 1600.000000. CPU Frequency is not max.
 65536      1000             2811.58            2811.55            0.044985


III. Server-
~ /usr/bin/ib_send_bw
Client -
~  ./ib_send_bw fe80::210:e000:129:6381%ib0

                    Send BW Test
 Dual-port       : OFF          Device         : mlx4_0
 Number of qps   : 1            Transport type : IB
 Connection type : RC           Using SRQ      : OFF
 TX depth        : 128
 CQ Moderation   : 100
 Mtu             : 2048[B]
 Link type       : IB
 Max inline data : 0[B]
 rdma_cm QPs     : OFF
 Data ex. method : Ethernet

 local address: LID 0x02 QPN 0x403f0 PSN 0xa155ac
 remote address: LID 0x02 QPN 0x403ef PSN 0x2b61b5

 #bytes     #iterations    BW peak[MB/sec]    BW average[MB/sec]   MsgRate[Mpps]
Conflicting CPU frequency values detected: 2401.000000 != 1600.000000. CPU Frequency is not max.
 65536      1000             2811.11            2811.10            0.044978

**Comment by aron-silverton** [comment]
@AnandBibhuti, if DNS and/or /etc/hosts is setup correctly, will hostnames placed on the command line be resolved to IPv6 addresses?

**Comment by AnandBibhuti** [comment]
Yes. Having proper entries in /etc/hosts and giving hostname (instead of IP address) in command line works fine.

**Comment by zoharbmellanox** [comment]
Thanks Anand .
we also verified this on our hosts and it works great.

appreciate the effort.

**Pull request merged**
